# Chiave univoca del progetto (presi dal tuo pom.xml: groupId:artifactId)
sonar.projectKey=it.uniroma2:HoopHub

# File da escludere COMPLETAMENTE (non verranno né analizzati né contati)
sonar.exclusions=**/*.css, **/*.fxml, src/main/resources/**/*.css