package it.uniroma2.hoophub.model;

import it.uniroma2.hoophub.enums.NotificationType;
import it.uniroma2.hoophub.enums.UserType;

import java.time.LocalDateTime;
import java.util.Objects;

/**
 * Immutable domain entity representing a user notification.
 *
 * <p>Notifications are generated by the system (via {@link it.uniroma2.hoophub.patterns.observer.NotificationBookingObserver})
 * when booking status changes occur.</p>
 *
 * <p>Uses <b>Builder pattern (GoF)</b> for construction.
 * State changes create new instances (functional immutability via {@link #markAsRead()}).</p>
 *
 * @author Elia Cinti
 * @version 1.0
 */
public class Notification {

    private final int id;
    private final String username;
    private final UserType userType;
    private final NotificationType type;
    private final String message;
    /** Nullable - null for system notifications not related to bookings. */
    private final Integer bookingId;
    private final boolean isRead;
    private final LocalDateTime createdAt;

    private Notification(Builder builder) {
        this.id = builder.id;
        this.username = builder.username;
        this.userType = builder.userType;
        this.type = builder.type;
        this.message = builder.message;
        this.bookingId = builder.bookingId;
        this.isRead = builder.isRead;
        this.createdAt = builder.createdAt;
    }

    // ========================================================================
    // PUBLIC BUSINESS OPERATIONS
    // ========================================================================

    /**
     * Creates a new Notification marked as read.
     *
     * <p>Returns a new instance (immutability pattern).</p>
     *
     * @return new Notification with isRead=true
     */
    public Notification markAsRead() {
        return new Builder()
                .from(this)
                .isRead(true)
                .build();
    }

    /**
     * Checks if notification is unread.
     *
     * @return true, if not yet read
     */
    public boolean isUnread() {
        return !isRead;
    }

    // ========================================================================
    // PUBLIC GETTERS
    // ========================================================================

    public int getId() {
        return id;
    }

    public String getUsername() {
        return username;
    }

    public UserType getUserType() {
        return userType;
    }

    public NotificationType getType() {
        return type;
    }

    public String getMessage() {
        return message;
    }

    /**
     * Gets associated booking ID (nullable).
     *
     * @return booking ID or null for system notifications
     */
    public Integer getBookingId() {
        return bookingId;
    }

    public boolean isRead() {
        return isRead;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    // ========================================================================
    // BUILDER CLASS
    // ========================================================================

    /**
     * Builder for Notification with fluent API and copy support.
     */
    public static class Builder {
        private int id;
        private String username;
        private UserType userType;
        private NotificationType type;
        private String message;
        private Integer bookingId;
        private boolean isRead = false;
        private LocalDateTime createdAt = LocalDateTime.now();

        public Builder id(int id) {
            this.id = id;
            return this;
        }

        public Builder username(String username) {
            this.username = username;
            return this;
        }

        public Builder userType(UserType userType) {
            this.userType = userType;
            return this;
        }

        public Builder type(NotificationType type) {
            this.type = type;
            return this;
        }

        public Builder message(String message) {
            this.message = message;
            return this;
        }

        public Builder bookingId(Integer bookingId) {
            this.bookingId = bookingId;
            return this;
        }

        /** Legacy alias for backwards compatibility. */

        public Builder isRead(boolean isRead) {
            this.isRead = isRead;
            return this;
        }

        public Builder createdAt(LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * Copies all fields from an existing notification.
         * Used by markAsRead() for immutable updates.
         *
         * @param notification source to copy from
         * @return this builder
         */
        public Builder from(Notification notification) {
            this.id = notification.id;
            this.username = notification.username;
            this.userType = notification.userType;
            this.type = notification.type;
            this.message = notification.message;
            this.bookingId = notification.bookingId;
            this.isRead = notification.isRead;
            this.createdAt = notification.createdAt;
            return this;
        }

        public Notification build() {
            validateRequiredFields();
            return new Notification(this);
        }

        private void validateRequiredFields() {
            if (username == null || username.trim().isEmpty())
                throw new IllegalStateException("username required");
            if (userType == null)
                throw new IllegalStateException("userType required");
            if (type == null)
                throw new IllegalStateException("type required");
            if (message == null || message.trim().isEmpty())
                throw new IllegalStateException("message required");
            if (createdAt == null)
                throw new IllegalStateException("createdAt required");
        }
    }

    // ========================================================================
    // UTILITY METHODS
    // ========================================================================

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Notification that = (Notification) o;
        return id == that.id;
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    @Override
    public String toString() {
        return "Notification{" +
                "id=" + id +
                ", recipient='" + username + '\'' +
                ", type=" + type +
                ", message='" + message + '\'' +
                ", isRead=" + isRead +
                '}';
    }
}